# Generated by Django 4.0.10 on 2023-11-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfEvent', models.CharField(max_length=100)),
                ('descOfEvent', models.TextField()),
                ('placeOfEvent', models.CharField(max_length=100)),
                ('dateOfEvent', models.DateField()),
                ('numOfVol', models.IntegerField()),
                ('eventPoster', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
