# Generated by Django 4.0.10 on 2023-11-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postevent',
            name='minAge',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
