# Generated by Django 4.0.10 on 2023-12-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntra', '0003_postevent_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
            ],
        ),
    ]
